#!/bin/bash -e

if [[ $# -eq 0 ]]; then # for displaying all branches
    headref=$(symbolic-ref HEAD | sed -e 's|^refs/heads/||') # get current branch
    echo "*$headref"
    cd .zit/refs/heads
    ls | grep -vxF $headref
elif [[ $1 == -d ]]; then
    rm -f .zit/refs/heads/$2
else
    update-ref refs/heads/$1 ${2-HEAD}
fi
