#!/bin/bash -e

echo tree $1 > .zit/commit.tmp
shift
while [[ $1 == -p ]]; do
    echo parent $2 >> .zit/commit.tmp
    shift; shift
done
echo author "Joe Mou <joe@mou.fo> $(date +'%s %z')" >> .zit/commit.tmp
echo committer "Joe Mou <joe@mou.fo> $(date +'%s %z')" >> .zit/commit.tmp
echo >> .zit/commit.tmp
cat >> .zit/commit.tmp

./hash-object commit .zit/commit.tmp
