#!/bin/bash -e

mkdir -p "$1/.zit/objects"
mkdir -p "$1/.zit/refs/heads"
echo 'ref: refs/heads/master' > "$1/.zit/HEAD"

# for git compatibility
ln -s .zit "$1/.git"
mkdir -p "$1/.git/info"
echo .zit > "$1/.git/info/exclude"
