#!/usr/bin/python

# read-tree.c:unpack_trees_rec
import struct
import subprocess
import sys

import index

_, tree_sha1 = sys.argv
tree = subprocess.check_output(['cat-file', 'tree', tree_sha1])
entries = []
while tree:
    header, rest = tree.split('\0', 1)
    mode, filename = header.split(' ', 1)
    rawsha1 = rest[:20]
    tree = rest[20:]
    # TODO handle directories
    if mode != '040000':
        entries.append((filename, int(mode, 8), rawsha1))

index.write_index(entries)
