#!/usr/bin/python

# write-tree.c
import subprocess

import index

entries = index.read_index()
# TODO write directories recursively? groupby?
f = open('.zit/tree.tmp', 'w')
for filename, mode, rawsha1 in entries:
    f.write('{:o} '.format(mode))
    f.write(filename)
    f.write('\0')
    f.write(rawsha1)
f.close()

subprocess.check_call(['hash-object', 'tree', '.zit/tree.tmp'])
